name: Build GBA ROM

on:
  workflow_dispatch:
  push:

jobs:
  build:
    runs-on: ubuntu-latest

    container:
      image: devkitpro/devkitarm:latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Build ROM
        run: |
          make

      - name: Upload ROM
        uses: actions/upload-artifact@v4
        with:
          name: balatro-gba
          path: |
            **/*.gba
